// Type definitions
export interface ContentItem {
  _id: string | number
  image: string
  alt: string
  text: string
  text1: string
  title: string
  nav: string[]
  link: string
}

// Combine all contentData into a single array
export const allContentData: ContentItem[] = [
  {
    _id: 1,
    title: "Machine Learning Fundamentals",
    image: "/machine-learning-fundamentals.jpg",
    alt: "AI Model",
    link: "/projects",
    text: "Discover the power of",
    text1: "artificial intelligence",
    nav: ["AI", "Machine Learning"],
  },
  {
    _id: 2,
    title: "Deep Learning Networks",
    image: "/deep-learning-networks.jpg",
    alt: "Neural Network",
    link: "/projects",
    text: "Explore deep neural",
    text1: "network architectures",
    nav: ["Deep Learning", "Neural Networks"],
  },
  {
    _id: 3,
    title: "Computer Vision Systems",
    image: "/computer-vision-systems.jpg",
    alt: "Computer Vision",
    link: "/projects",
    text: "Advanced image",
    text1: "recognition technology",
    nav: ["Computer Vision", "Image Processing"],
  },
  {
    _id: 4,
    title: "Natural Language Processing",
    image: "/natural-language-processing.jpg",
    alt: "NLP Technology",
    link: "/projects",
    text: "Understanding human",
    text1: "language with AI",
    nav: ["NLP", "Text Analysis"],
  },
  {
    _id: 5,
    title: "Reinforcement Learning",
    image: "/reinforcement-learning.jpg",
    alt: "RL Algorithm",
    link: "/projects",
    text: "Learning through",
    text1: "trial and error",
    nav: ["Reinforcement Learning", "Algorithms"],
  },
  {
    _id: 6,
    title: "Data Science Analytics",
    image: "/data-science-analytics.jpg",
    alt: "Data Analytics",
    link: "/projects",
    text: "Extracting insights",
    text1: "from complex data",
    nav: ["Data Science", "Analytics"],
  },
  {
    _id: 7,
    title: "Robotics Integration",
    image: "/robotics-integration.jpg",
    alt: "Robotics",
    link: "/projects",
    text: "AI-powered robotic",
    text1: "automation systems",
    nav: ["Robotics", "Automation"],
  },
  {
    _id: 8,
    title: "Predictive Modeling",
    image: "/predictive-modeling.jpg",
    alt: "Predictive Models",
    link: "/projects",
    text: "Forecasting future",
    text1: "trends and patterns",
    nav: ["Prediction", "Modeling"],
  },
  {
    _id: 9,
    title: "Edge AI Computing",
    image: "/edge-ai-computing.jpg",
    alt: "Edge Computing",
    link: "/projects",
    text: "AI processing at",
    text1: "the network edge",
    nav: ["Edge AI", "Computing"],
  },
  {
    _id: 10,
    title: "Quantum Machine Learning",
    image: "/quantum-machine-learning.jpg",
    alt: "Quantum ML",
    link: "/projects",
    text: "Quantum-enhanced",
    text1: "learning algorithms",
    nav: ["Quantum", "Machine Learning"],
  },
  {
    _id: 11,
    title: "Autonomous Systems",
    image: "/autonomous-systems.jpg",
    alt: "Autonomous Tech",
    link: "/projects",
    text: "Self-driving and",
    text1: "autonomous vehicles",
    nav: ["Autonomous", "Systems"],
  },
  {
    _id: 12,
    title: "AI Ethics & Safety",
    image: "/ai-ethics-safety.jpg",
    alt: "AI Ethics",
    link: "/projects",
    text: "Responsible AI",
    text1: "development practices",
    nav: ["Ethics", "AI Safety"],
  },
  {
    _id: 13,
    title: "Generative AI Models",
    image: "/generative-ai-models.jpg",
    alt: "Generative AI",
    link: "/projects",
    text: "Creating new content",
    text1: "with AI generation",
    nav: ["Generative AI", "Content Creation"],
  },
  {
    _id: 14,
    title: "Federated Learning",
    image: "/federated-learning.jpg",
    alt: "Federated Learning",
    link: "/projects",
    text: "Distributed machine",
    text1: "learning systems",
    nav: ["Federated Learning", "Distributed"],
  },
  {
    _id: 15,
    title: "AI Model Optimization",
    image: "/ai-model-optimization.jpg",
    alt: "Model Optimization",
    link: "/projects",
    text: "Efficient model",
    text1: "performance tuning",
    nav: ["Optimization", "Performance"],
  },
  {
    _id: 16,
    title: "Multimodal AI Systems",
    image: "/multimodal-ai-systems.jpg",
    alt: "Multimodal AI",
    link: "/projects",
    text: "Combining multiple",
    text1: "data modalities",
    nav: ["Multimodal", "AI Systems"],
  },
  {
    _id: 17,
    title: "AI-Powered Healthcare",
    image: "/ai-powered-healthcare.jpg",
    alt: "Healthcare AI",
    link: "/projects",
    text: "Medical diagnosis",
    text1: "and treatment AI",
    nav: ["Healthcare", "Medical AI"],
  },
  {
    _id: 18,
    title: "Smart City Solutions",
    image: "/smart-city-solutions.jpg",
    alt: "Smart Cities",
    link: "/projects",
    text: "Urban intelligence",
    text1: "and optimization",
    nav: ["Smart Cities", "Urban Tech"],
  },
]
